"""Bake a directory of trikedb YAML files into an importable Python module.

Workers ships code, not files: there is no filesystem to read a graph
from, and no object store unless you add one and pay for it. Pyodide does
give the Worker an in-memory filesystem, though, so the graph can travel
as Python strings and be written out at import time (src/entry.py does
that).

The output, src/graphdata.py, is generated -- do not edit it, and do not
commit it. Re-run this whenever the graph changes, then deploy:

    python3 tools/embed_graph.py                  # the bundled sample
    python3 tools/embed_graph.py path/to/graphs   # your own
    uv run pywrangler deploy

Every *.yaml in the directory is embedded, which is what a workspace
needs: the entry file names its members by relative path and they all
have to land in the same directory on the other side.
"""

import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent
# The demo graph that ships with trikedb, five members plus the workspace
# that unions them.
DEFAULT_SRC = ROOT.parent.parent / "examples" / "graphs" / "trike"
SRC = pathlib.Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else DEFAULT_SRC
OUT = ROOT / "src" / "graphdata.py"


def main() -> None:
    files = sorted(p for p in SRC.glob("*.yaml"))
    if not files:
        raise SystemExit(f"no *.yaml under {SRC}")

    parts = ['"""Generated by tools/embed_graph.py. Do not edit."""\n', "FILES = {\n"]
    for p in files:
        # repr() of the text, so any quoting in the YAML survives without
        # an escaping pass of our own.
        parts.append(f"    {p.name!r}: {p.read_text(encoding='utf-8')!r},\n")
    parts.append("}\n")
    OUT.write_text("".join(parts), encoding="utf-8")

    total = sum(p.stat().st_size for p in files)
    print(f"{OUT} <- {len(files)} files, {total:,} bytes")
    for p in files:
        print(f"  {p.name} ({p.stat().st_size:,})")


if __name__ == "__main__":
    main()
